### ISSUE TITLE
Icon not appearing in gnome 3.14

### ISSUE THREAD

**Issue by jusa213** [awamper/gnote-integration#13]
Hello

Thanks for that nice extension.
Tried it but it does not work reliable in gnome 3.14 (debian jessie).
As for tomboy - the icon only appears if tomboy is opened. It disappears if tomboy is closed.
As for gnote - it does not seem to recognize gnote. Even if gnote is opened the icon does not appear.

Would it be possible to dig into this and fix this?
If more information is needed I can provide it. But it's easily reproducible. Happens with plain debian 8 install for example.

Thanks and regards

**Comment by jusa213** [comment]
This problem can however be solved.

Create a file called gnote.desktop in .config/autostart/ and put the following as content: 
[Desktop Entry]
Name=gnote
Exec=gnote --background 
Type=Application
Categories=GNOME;GTK;System;Utility;

That way gnote is started in background during log in and the extension is shown as it is supposed to.

**Comment by kanazir** [comment]
That does not work. Gnome Shell 3.14.

**Comment by awamper** [comment]
>> As for tomboy - the icon only appears if tomboy is opened. It disappears if tomboy is closed.
Does tomboy running in the background when its closed?
>> As for gnote - it does not seem to recognize gnote. Even if gnote is opened the icon does not appear.
Did you switch to Gnote in the settings?

**Comment by kanazir** [comment]
You can't access the settings because the extension cannot be installed - it refuses to run and it is not showing in the installed extensions.
I made you small screencast, you can download it from here: http://vlajko.com/gnote.webm

During installation, gnote is running, as you can see at the end of the video. GNOME Shell 3.14.4.

**Comment by awamper** [comment]
Enter in the terminal:
> gnome-shell --replace

try install extension and paste errors here.

**Comment by kanazir** [comment]
Archive:  /tmp/EJA80X.shell-extension.zip
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/extension.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/note_content_view.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/libs/sax.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/constants.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/note_page_chooser.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/tooltips.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/gnote_list_item_buttons.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/shared.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/note_date_label.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/note_previewer_content_view.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/gnote_list_view_snippet_renderer.js  
   creating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/schemas/
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/schemas/gschemas.compiled  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/images/page-indicator-active.svg  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/gnote_note.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/client_base.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/images/page-indicator-inactive-has-items.svg  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/desktop_notes.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/images/page-indicator-checked.svg  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/gnote_toolbar.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/prefs.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/status_bar.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/utils.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/libs/moment.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/desktop_note_container.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/stylesheet.css  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/prefs_keys.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/gnote_client.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/buttons_bar.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/gnote_list_view_renderer_base.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/LICENSE  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/gnote_list_view_title_renderer.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/schemas/org.gnome.shell.extensions.gnote-integration.gschema.xml  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/desktop_note_view.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/list_view.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/images/page-indicator-hover.svg  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/dialog.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/popup_dialog.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/note_color_chooser.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/gnote_integration.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/images/resize.svg  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/tomboy_client.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/page_indicators.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/link_preview_dialog.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/confirmation_modal_dialog.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/dialog_note_view.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/desktop_note_toolbar.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/link_previewers.js  
  inflating: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/images/page-indicator-inactive.svg  
 extracting: /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/metadata.json

**Comment by awamper** [comment]
There is no errors. Try download https://github.com/awamper/gnote-integration/archive/3.14.zip and extract it to 
> /home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/ (remove this dir if exists) 

then \<Alt\>\<F2\> -\> r -\> \<Enter\> and enable extension from gnome tweak tool.

**Comment by kanazir** [comment]
OK, we have a progress :)

cd ~/.local/share/gnome-shell/extensions
unzip ~/Download/gnote-integration-3.14.zip
mv gnote-integration-3.14/ gnote_integration@awamper.gmail.com

then restart and extension is shown in the list, but with the triangle - it has an error.
When I try to open its settings, I get:

`Error: Requiring GConf, version none: Typelib file for namespace 'GConf' (any version) not found

Stack trace:
  @/home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/tomboy_client.js:3
  @/home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/utils.js:12
  @/home/canny/.local/share/gnome-shell/extensions/gnote_integration@awamper.gmail.com/prefs.js:11
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:80
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:95
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:260
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  main@resource:///org/gnome/shell/extensionPrefs/main.js:398
  @<main>:1`

It looks like my distro is missing something, right?

**Comment by awamper** [comment]
You need GConf or GConf2 i'm not sure.

**Comment by awamper** [comment]
try 
> gir1.2-gconf-2.0

**Comment by kanazir** [comment]
That is it! gir1.2-gconf-2.0 package was missing.
Problem solved!
Thanks! :)
