### ISSUE TITLE
update

### ISSUE THREAD

**Issue by joshp23** [awamper/gnote-integration#21]
Running Gnome V. 3.24.2, any chance on an update? I love this extension and miss it since upgrade!

**Comment by awamper** [comment]
Probably not, sorry.

**Comment by joshp23** [comment]
it appears as if #24 updates this. how about approving and updating with gnome.org?

**Comment by awamper** [comment]
i tried it and my shell crashed several times, so im not gonna update it on gnome.org. You could install it from git if you want to.

**Comment by joshp23** [comment]
That's my bad. I posted with haste before testing. I tested and it failed, too. Neglected to come back and update this. I've officially given up on gnote besides. 

Thanks anyway!
